### ISSUE TITLE
2.3.0 release checklist

### ISSUE THREAD

**Issue by wazzamatazz** [intelligentplant/IndustrialAppStore.ClientTools.DotNet#63]
- [ ] Remove pre-release version flag
- [ ] Prepare release notes
- [ ] Review examples and documentation
- [ ] Publish NuGet packages

**Comment by wazzamatazz** [comment]
Version 3.0.0 will be released instead
